import { lazy, Suspense } from "react";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata = {
  title: "Dropshipping Site",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {/* <Suspense fallback={<div>Loading...</div>}> */}
        <Navbar />
        {/* </Suspense> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
