import { lazy, Suspense } from "react";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import { Overpass } from "next/font/google";
import Navigation from "./components/Navigation";

export const metadata = {
  title: "Dropshipping Site",
  description: "Generated by create next app",
};

const overpass = Overpass({
  weight: "400",
  subsets: ["latin"],
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${overpass.className} `}>
        {/* <Suspense fallback={<div>Loading...</div>}> */}
        <Navbar />
        {/* </Suspense> */}
        {children}
        <Footer />
      </body>
    </html>
  );
}
